### ISSUE TITLE
Adding Prism language support to code blocks

### ISSUE THREAD

**Issue by tansawit** [cosmos/vuepress-theme-cosmos#109]
Is there anyway to add additional languages to the Prism.js configuration being used by this theme? Specifically I'm looking to add support Solidity but can't figure out where to add the CSS and JS files or if something else need to be done

**Comment by lovincyrus** [comment]
Hi @tansawit !

We're currently using a [custom `code-block` component](https://github.com/tendermint/cosmos-ui/blob/develop/src/CodeBlock/CodeBlock.vue) for this docs theme.

Additional languages must be imported manually to this file: https://github.com/tendermint/cosmos-ui/blob/develop/src/CodeBlock/CodeBlock.vue#L403

[Prism.js](https://prismjs.com/#supported-languages) supports `Solidity (Ethereum) - solidity, sol`.

I'll make sure to add the `sol` support and release it in the upcoming version 👌

## Related:
- https://github.com/CosmWasm/docs/pull/47#issuecomment-651242471
- syntax highlighting for rust https://github.com/tendermint/cosmos-ui/pull/201

**Comment by tansawit** [comment]
Thank you for such a quick response! Looking forward to using it in the new release 👍
