### ISSUE TITLE
Question: build multiple docs then merge

### ISSUE THREAD

**Issue by marbar3778** [cosmos/vuepress-theme-cosmos#113]
I would like to build the spec docs and the tendermint docs separately and then merge the outputs to create one doc page. Is this possible?

**Comment by lovincyrus** [comment]
@marbar3778 Vuepress docs take markdown files as its inputs. In the current pre-build process, [a script](https://github.com/tendermint/tendermint/blob/master/docs/pre.sh) clones the spec folder and creates a build-ready dist in `.vuepress/dist`. 

**_RE_**: building the spec and tendermint docs separately

I'm not sure if that's possible. It's either you add the spec files to tendermint docs or you add tendermint files to spec docs.

How are you trying to config the spec docs differently? When do you need the spec files during the build process?

**Comment by lovincyrus** [comment]
Feel free to reopen this issue if you have any follow up questions 👌
