### ISSUE TITLE
JetBrains Mono GET request fails with 404 error

### ISSUE THREAD

**Issue by girlandhercode** [cosmos/vuepress-theme-cosmos#122]
Thank you for creating and sharing this theme. I truly appreciate it.

The `GET` requests originating from the  `src` urls referenced below in `vuepress-theme-cosmos/styles/index.styl`, return a `404` error.  

The url you are requesting seems not to serve these files anymore (or possibly the `404` could be a result of `raw.githubusercontent.com` returning an incorrect `Content-Type` vs. what is specified in the request header's `Accept` field as shown in the [Request](#user-content-request-headers) / [Response](#user-content-response-headers) code blocks below). 

https://github.com/cosmos/vuepress-theme-cosmos/blob/15ce52a3eb704756938f90485321723465126c19/styles/index.styl#L22-L29

### This font is available from the following CDN (as well as others, I'm sure):

`https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff/JetBrainsMono-Regular.woff`
`https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff2/JetBrainsMono-Regular.woff2`

**NOTE**: This CDN does not seem to host any `.ttf` versions, only `.eot`, `.woff`, and `.woff2`

---

### Request headers <a href="#user-content-request-headers" id="request-headers">#</a>:
```http
GET /JetBrains/JetBrainsMono/master/web/woff2/JetBrainsMono-Regular.woff2 HTTP/1.1
Host: raw.githubusercontent.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
Accept: application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: identity
Origin: https://docs.cosmos.network
DNT: 1
Connection: keep-alive
Referer: https://docs.cosmos.network/v0.39/assets/css/0.styles.bbf05c60.css
Pragma: no-cache
Cache-Control: no-cache
```

### Response headers <a href="#user-content-response-headers" id="response-headers">#</a>:
```http
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 14
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Content-Type: text/plain; charset=utf-8
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 899A:4CC4:198CAF:1D3124:5F7E1EEA
Accept-Ranges: bytes
Date: Wed, 07 Oct 2020 20:03:33 GMT
Via: 1.1 varnish
X-Served-By: cache-wdc5556-WDC
X-Cache: MISS, HIT
X-Cache-Hits: 0, 2
X-Timer: S1602101014.935106,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 271515b5e0f4ec4f41c842a52ee0e13a43e0a16c
Expires: Wed, 07 Oct 2020 20:08:33 GMT
Source-Age: 43
```

**Comment by lovincyrus** [comment]
Hi @girlandhercode! Thanks for creating this issue.

> `https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff/JetBrainsMono-Regular.woff`
> `https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff2/JetBrainsMono-Regular.woff2`
> 
> **NOTE**: This CDN does not seem to host any `.ttf` versions, only `.eot`, `.woff`, and `.woff2`

I was able to find `.woff`, `.woff2`, and `.ttf` from this file path [`JetBrains/JetBrainsMono/fonts` ](https://github.com/JetBrains/JetBrainsMono/tree/master/fonts). It seems like `.eot` is no longer available from the repo. I'll go ahead and get rid of the following line.

https://github.com/cosmos/vuepress-theme-cosmos/blob/15ce52a3eb704756938f90485321723465126c19/styles/index.styl#L24
