### ISSUE TITLE
Link to "App Anatomy" subsection of the docs don't seem to work

### ISSUE THREAD

**Issue by ebuchman** [cosmos/vuepress-theme-cosmos#140]
When clicking through the documentation, at some point you get to: https://docs.cosmos.network/v0.40/basics/app-anatomy.html

But when I try to go to that link directly, I'm taken to a broken version of the SDK docs homepage (without a working sidebar)

Other links from clicking through the docs seem to work fine.

**Comment by lovincyrus** [comment]
Test on https://github.com/cosmos/cosmos-sdk/pull/7830

![image](https://user-images.githubusercontent.com/1021101/98298226-7ed7d300-1f6a-11eb-9d2c-cb1753290d20.png)

**Comment by lovincyrus** [comment]
Fixed
