### ISSUE TITLE
Customizable top banner

### ISSUE THREAD

**Issue by orkunkl** [cosmos/vuepress-theme-cosmos#167]
I really like the top banner in https://docs.cosmos.network. But I could not find how to enable it at https://docs.cosmwasm.com. It would be great if you could document it or allow theme users to define custom banners.

**Comment by lovincyrus** [comment]
Hi! We currently do not provide custom banners for custom sites. However, if you really need to enable it at your own site, you may copy the code https://github.com/cosmos/vuepress-theme-cosmos/blob/develop/global-components/TmTopBanner.vue and add a custom .vue file to your `docs/.vuepress/components` folder.

Ref: https://github.com/cosmos/sdk-tutorials/tree/master/.vuepress/components
