### ISSUE TITLE
next button should be above previous

### ISSUE THREAD

**Issue by hxrts** [cosmos/vuepress-theme-cosmos#45]
the default action is for readers to move forward, so this should be how the page is organized

original [issue](https://github.com/cosmos/sdk-tutorials/issues/315)

--

ubuntu / firefox 76

![](https://i.imgur.com/12HSGrq.png)

**Comment by fadeev** [comment]
@hxrts Hi! Thanks for reporting this bug. Will be fixed in the next version.

**Comment by fadeev** [comment]
<img width="1009" alt="Screenshot 2020-05-29 at 01 36 52" src="https://user-images.githubusercontent.com/332151/83191072-e59bc980-a14c-11ea-9aff-b36cb5ce7536.png">

**Comment by hxrts** [comment]
fantastic, thank you!
