### ISSUE TITLE
deep link to github source

### ISSUE THREAD

**Issue by hxrts** [cosmos/vuepress-theme-cosmos#59]
unless you have edit permission to the source text, you get a page that says you must have additional privileges, rather than a link to the file.

**Comment by lovincyrus** [comment]
Hi @hxrts !

Are you suggesting that we should send users to the `blob` page instead of the `edit` page?

_**e.g.**_ https://docs.cosmos.network/

`blob`: https://github.com/cosmos/cosmos-sdk/blob/master/docs/README.md
`edit`: https://github.com/cosmos/cosmos-sdk/edit/master/docs/README.md

**Comment by hxrts** [comment]
hmm, I guess not. edit is probably correct? it's just unfortunate that if you don't already have edit rights you get a "fork this repo" screen before you can see the code.

**Comment by lovincyrus** [comment]
> hmm, I guess not. edit is probably correct? it's just unfortunate that if you don't already have edit rights you get a "fork this repo" screen before you can see the code.

`edit` is probably the correct solution in this case. The users are required to fork and edit the files anyway if they do not have the right permissions. Will close this for now and reopen until we have a better way of handling this.
